services:
  - type: web
    name: clientflow-api
    runtime: node
    rootDir: backend
    buildCommand: npm install -g bun && bun install
    startCommand: bun run src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_APP_PASSWORD
        sync: false
      - key: CLIENT_URL
        sync: false
